#!/usr/bin/env node
import { randomBytes } from 'node:crypto'
import { chmodSync, mkdirSync, readFileSync, realpathSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { homedir } from 'node:os'
import { dirname, join } from 'node:path'
import type { Readable, Writable } from 'node:stream'
import { fileURLToPath } from 'node:url'
import { parseArgs } from 'node:util'
import { createMcpServer, httpBackend, serveStdio, tabBackend, type ChatBackend } from './mcp.js'
import { DEFAULT_HOST, DEFAULT_PORT, isLoopback, startServer, type BridgeServer } from './server.js'
import type { Health } from './tab.js'

export const VERSION = (createRequire(import.meta.url)('../package.json') as { version: string }).version
export const TOKEN_ENV = 'REBELLM_BRIDGE_TOKEN'

export const USAGE = `Usage: rebellm-bridge [options]
       rebellm-bridge claude [launcher options] [claude arguments]

Lets Claude Code (MCP or rebellm-claude) and OpenAI-style clients use the model in your RebeLLM tab.

  claude ...      run Claude Code on the tab's model, the same as rebellm-claude
  --port <n>      port for the tab and the HTTP API (default ${DEFAULT_PORT})
  --host <addr>   address to listen on (default ${DEFAULT_HOST}; anything else exposes the model)
  --token <t>     token the tab must present (default: ${TOKEN_ENV}, else ~/.rebellm-bridge/token)
  --wait <s>      seconds a request waits for the tab and its model (default 120)
  --mcp           serve MCP over stdio as well (Claude Code starts the bridge this way)
  --quiet         no log line per request (arrival, queue, first token, end)
  --version       print the version
  --help          print this help`

export interface CliOptions {
  port: number
  host: string
  token?: string
  waitSec: number
  mcp: boolean
  quiet: boolean
  help: boolean
  version: boolean
}

export function parseCli(argv: string[]): CliOptions | { error: string } {
  let v
  try {
    v = parseArgs({
      args: argv,
      strict: true,
      options: {
        port: { type: 'string' },
        host: { type: 'string' },
        token: { type: 'string' },
        wait: { type: 'string' },
        mcp: { type: 'boolean' },
        quiet: { type: 'boolean' },
        help: { type: 'boolean', short: 'h' },
        version: { type: 'boolean', short: 'v' },
      },
    }).values
  } catch (e) {
    return { error: (e as Error).message }
  }
  const port = Number(v.port ?? DEFAULT_PORT)
  if (!Number.isInteger(port) || port < 0 || port > 65535) return { error: `--port ${v.port} is not a port number` }
  const waitSec = Number(v.wait ?? 120)
  if (!Number.isFinite(waitSec) || waitSec < 0) return { error: `--wait ${v.wait} is not a number of seconds` }
  const host = v.host ?? DEFAULT_HOST
  if (!host) return { error: '--host needs an address' }
  if (v.token !== undefined && !v.token.trim()) return { error: '--token needs a value' }
  return {
    port,
    host,
    ...(v.token !== undefined ? { token: v.token.trim() } : {}),
    waitSec,
    mcp: !!v.mcp,
    quiet: !!v.quiet,
    help: !!v.help,
    version: !!v.version,
  }
}

export const tokenFile = (home = homedir()) => join(home, '.rebellm-bridge', 'token')

export interface TokenChoice {
  token: string
  source: 'flag' | 'env' | 'file'
  /** Generated by this start; the only time it is printed. */
  created: boolean
  file: string
}

/** `--token`, else the environment, else the token file, created on first use. */
export function resolveToken(o: { flag?: string; env?: string; home?: string }): TokenChoice {
  const file = tokenFile(o.home)
  if (o.flag) return { token: o.flag, source: 'flag', created: false, file }
  if (o.env?.trim()) return { token: o.env.trim(), source: 'env', created: false, file }
  try {
    const stored = readFileSync(file, 'utf8').trim()
    if (stored) return { token: stored, source: 'file', created: false, file }
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code !== 'ENOENT') throw e
  }
  const token = randomBytes(24).toString('base64url')
  mkdirSync(dirname(file), { recursive: true, mode: 0o700 })
  writeFileSync(file, `${token}\n`, { mode: 0o600 })
  // An empty file left from before keeps its old mode otherwise.
  chmodSync(file, 0o600)
  return { token, source: 'file', created: true, file }
}

export interface Io {
  stdout: Writable
  stderr: Writable
  stdin: Readable
  env: NodeJS.ProcessEnv
  home?: string
}

export interface Running {
  /** Null when `--mcp` found another bridge on the port and uses that one. */
  server: BridgeServer | null
  backend: ChatBackend | null
  /** Resolves when the MCP client closes stdin; never without `--mcp`. */
  done: Promise<void>
  close(): Promise<void>
}

/** The `/health` of a bridge of ours at `base`; null when nothing or something else answers. */
export async function bridgeHealth(base: string): Promise<Health | null> {
  try {
    const r = await fetch(`${base}/health`, { signal: AbortSignal.timeout(2000) })
    const body = (await r.json()) as Health & { service?: unknown }
    return body.service === 'rebellm-bridge' ? body : null
  } catch {
    return null
  }
}

/** Anything but loopback lets other machines use the model; the HTTP API has no token. */
export const hostWarning = (host: string) =>
  isLoopback(host)
    ? null
    : `warning: listening on ${host} lets other machines use your model; the HTTP API has no token`

const urlHost = (host: string) => (host.includes(':') ? `[${host}]` : host)

/** Starts the bridge; throws a readable message when it cannot. */
export async function run(o: CliOptions, io: Io): Promise<Running> {
  // With --mcp, stdout is the MCP channel.
  const out = o.mcp ? io.stderr : io.stdout
  const say = (line: string) => void out.write(`${line}\n`)
  const log = (line: string) => say(`rebellm-bridge: ${line}`)
  const requestLog = o.quiet ? () => undefined : log
  const tok = resolveToken({
    ...(o.token ? { flag: o.token } : {}),
    ...(io.env[TOKEN_ENV] ? { env: io.env[TOKEN_ENV] } : {}),
    ...(io.home ? { home: io.home } : {}),
  })
  if (tok.created)
    say(
      `\nNew bridge token (stored in ${tok.file}):\n\n  ${tok.token}\n\n` +
        'Paste it into RebeLLM → Bridge and turn the switch on. It is printed only this once.\n',
    )
  const warning = hostWarning(o.host)
  if (warning) log(warning)

  let server: BridgeServer | null = null
  let backend: ChatBackend | null = null
  try {
    server = await startServer({
      host: o.host,
      port: o.port,
      token: tok.token,
      waitMs: o.waitSec * 1000,
      log,
      requestLog,
    })
    if (o.mcp) backend = tabBackend(server.tab, o.waitSec * 1000)
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code !== 'EADDRINUSE') throw e
    const probe = `http://${urlHost(isLoopback(o.host) ? o.host : DEFAULT_HOST)}:${o.port}`
    if (!o.mcp || !(await bridgeHealth(probe)))
      throw new Error(`port ${o.port} on ${o.host} is in use${o.mcp ? '' : ' (another rebellm-bridge?)'}`, {
        cause: e,
      })
    backend = httpBackend(probe)
    log(`using the bridge already running on ${probe}`)
  }

  if (server) {
    const where = `${urlHost(o.host)}:${server.port}`
    log(`${VERSION} listening on ${where}`)
    say(`  tab:    ws://${where}  (RebeLLM → Bridge)`)
    say(`  OpenAI: http://${where}/v1`)
    say(`  Claude: http://${where}  (Anthropic API; rebellm-claude runs Claude Code on it)`)
    say(
      `  token:  ${tok.source === 'flag' ? 'from --token' : tok.source === 'env' ? `from ${TOKEN_ENV}` : `in ${tok.file}`}`,
    )
    log('waiting for the RebeLLM tab')
  }

  let done: Promise<void> = new Promise(() => undefined)
  if (o.mcp && backend) {
    done = serveStdio(createMcpServer(backend, VERSION, requestLog), io.stdin, io.stdout)
  }
  return {
    server,
    backend,
    done,
    close: async () => {
      await server?.close()
    },
  }
}

/** The command line; resolves with the exit code once the bridge has stopped. */
export async function main(argv: string[], io: Io): Promise<number> {
  if (argv[0] === 'claude') {
    // Loaded here so the plain bridge never touches the launcher, and the two files can import each other.
    const { launch } = await import('./launcher.js')
    return launch(argv.slice(1), { stderr: io.stderr, env: io.env, ...(io.home ? { home: io.home } : {}) })
  }
  const o = parseCli(argv)
  if ('error' in o) {
    io.stderr.write(`rebellm-bridge: ${o.error}\n\n${USAGE}\n`)
    return 2
  }
  if (o.help || o.version) {
    io.stdout.write(`${o.help ? USAGE : VERSION}\n`)
    return 0
  }
  let running: Running
  try {
    running = await run(o, io)
  } catch (e) {
    io.stderr.write(`rebellm-bridge: ${(e as Error).message}\n`)
    return 1
  }
  const stop = new Promise<void>((resolve) => {
    process.once('SIGINT', resolve)
    process.once('SIGTERM', resolve)
  })
  await Promise.race([running.done, stop])
  await running.close()
  return 0
}

function invokedDirectly() {
  try {
    return !!process.argv[1] && realpathSync(process.argv[1]) === realpathSync(fileURLToPath(import.meta.url))
  } catch {
    return false
  }
}

if (invokedDirectly()) {
  const io: Io = { stdout: process.stdout, stderr: process.stderr, stdin: process.stdin, env: process.env }
  void main(process.argv.slice(2), io).then((code) => process.exit(code))
}
